apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  namespace: weatherapp
spec:
  type: NodePort
  selector:
    app: weatherapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
  